### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by solarjoe** [gcompris/GCompris-qt#213]
Here are other possible improvements:

explore_farm_animals:
- it could be possible to skip the first stage where you have to click each animal and get directly to the sound question and the quiz

simplepaint:

- it is not immediately clear that the top light blue color is the eraser, could be a eraser icon :)
- it is not immediately clear that there are other colors (no scroll bar, arrow, etc.)

maze:
- in the high levels of the maze (e.g. 25) Tux walks long (random?) distances if clicking somewhere out of reach. Is this a feature?

melody:
- it is a bit strange that the sound right before the melody to remember is someone hitting all bars up and down. could instead be a visual baton (conducting) or that knock knock knock when a conductor is asking for attention right before a song hitting is desk with the baton.

**Comment by petitlapin** [comment]
I created multiple tasks for simplepaint (https://phabricator.kde.org/T8085 and https://phabricator.kde.org/T8086) and melody (https://phabricator.kde.org/T8055).

For explore_farm_animals, you can go on sound question and quiz by going to next level. However the design is faulty there as the level does not increment. This is due to other activities (explore_music, explore_world...) that share the same code and have multiple levels (along with the "sublevels" that are the sound/quiz). We need to think of a better way to make it more natural.

**Comment by solarjoe** [comment]
On melody, I just checked the Gtk+, what I was referring to it the same there. I don't mean the visual feedback while the melody play, but right before it starts, the quick sequence of all notes. This is a bit strange and I guess a "knock knock knock" would "feel" more natural.

**Comment by petitlapin** [comment]
ok, I updated the task with your comment.
Thank you

**Comment by petitlapin** [comment]
Hi,

all the issues are fixed and in the release 0.91 we did a few days ago.
Thank you for reporting the bugs,

Johnny
