### ISSUE TITLE
Empty squares in "build the same model" with greek language

### ISSUE THREAD

**Issue by Wizard13** [gcompris/GCompris-qt#247]
In 0.95 and 0.96 when using "build the same model" with greek language I get empty squares. With english language I get english letters. Also, the arrow buttons and the crane appear distorted when the screen resolution is not wide (in my case 1280x1024). Version 0.91 doesn't have these issues (I get english letters with greek language and no distortion). Please see folllowing pictures:

0.96, greek language, 1280x1024
![Build_the_same_model_0 96_1280x1024_greek](https://user-images.githubusercontent.com/7610978/55722876-251aca00-5a10-11e9-8d72-e7a93ed2de51.jpg)

0.96, greek language, 1366x768
![Build_the_same_model_0 96_1366x768_greek](https://user-images.githubusercontent.com/7610978/55722893-32d04f80-5a10-11e9-9d77-f06b0217f04e.jpg)

0.91, greek language, 1280x1024
![Build_the_same_model_0 91_1280x1024_greek](https://user-images.githubusercontent.com/7610978/55722928-4da2c400-5a10-11e9-8bdb-cd0d3f33bbd1.jpg)

0.91, greek language, 1366x768
![Build_the_same_model_0 91_1366x768_greek](https://user-images.githubusercontent.com/7610978/55722941-572c2c00-5a10-11e9-8484-19eb2f063b43.jpg)

**Comment by petitlapin** [comment]
Hi,

thank you for the report.

The error is because we translated the displayed words with non ascii letters: https://github.com/gcompris/GCompris-qt/blob/master/src/activities/crane/crane.js#L71
I'll contact the Greek person to know how to handle this (either we add new images for the Greek letters but it will be too much as we'll have to do it for other locales too or we keep them in English which is lighter for the final executable).

**Comment by petitlapin** [comment]
Fixed in https://phabricator.kde.org/R883:1539796 and https://phabricator.kde.org/R883:1539797
We won't plan a bug fix for now, it will be fixed in next release. The activity is playable for higher levels where we don't use specific translated words.

Thank you for the report
