### ISSUE TITLE
Watercycle broken starting after 2.1

### ISSUE THREAD

**Issue by kentavv** [gcompris/GCompris-qt#279]
On a 1920x1080 landscape screen, Watercycle is broken in 2.3 and 2.2, sometime after 2.1. No amount of clicking will cause the clouds to rain. The screen is split in half between game and text. Thought problem had something to do with isVertical or textOnSide, but have not found a solution.

**Comment by petitlapin** [comment]
@Animtim you did some updates on it, can you take a look?

**Comment by Animtim** [comment]
Can you tell me on which operating system you have this issue, and how did you install gcompris (from which source) ?
Here it works.

That the screen is split in half image/half text is expected (as the image was redone in a square ratio to work on any screen ratio without distortion). Also the click on the cloud is activated only after it finishes moving above the mountains.

**Comment by Animtim** [comment]
Ah, I can reproduce when building with Qt 5.15 (as I use 5.12 for main development and for the packages, I didn't notice it before). I'll take a look to fix it.

**Comment by Animtim** [comment]
Ouch, I found that this issue is caused by a critical bug in Qt 5.15, reported almost 2 years ago and still not fixed :( 
https://bugreports.qt.io/browse/QTBUG-85935

I'll make a workaround, hoping it gets fixed at some point. And then I'll have to double check all the other places where we use transitions...

**Comment by Animtim** [comment]
Fixed. Thanks for the report!
