### ISSUE TITLE
Mouse "cursor" placement with multiple monitors

### ISSUE THREAD

**Issue by jfcaron3** [gcompris/GCompris-qt#290]
I couldn't figure out how to take a screenshot that shows this nicely, but for the game "Découvre la souris" in French, the blue ducky cursor is misplaced, presumably because I have a second monitor.  
![Screenshot at 2023-10-14 11-17-26](https://github.com/gcompris/GCompris-qt/assets/7063767/5809138e-94eb-47dc-a79c-29ae1fd6f502)

The blue ducky is supposed to follow the cursor around, but it's offset unless I bring the cursor to the right-most edge of the primary monitor.

**Comment by petitlapin** [comment]
Hi,

thank you for the report, we'll take a look! It seems we don't take care of when the mouse leaves the screen (I can reproduce in windowed mode too)

**Comment by Animtim** [comment]
Hi,
Actually, this is by design: the duck is not supposed to follow the mouse position, but to follow the mouse movements, which is quite different. In most cases, the duck will not be at the mouse position, unless the user plays with the offset to make them match intentionally, as the duck is initialized at a fixed position and can only move on a restricted area in the center of the window (it can't go to the top, bottom and left borders). So users can play changing the offset between cursor and duck positions by moving the cursor in the top/left/bottom stripes and back to the "move" area, or by clicking on the arrow buttons on the top-right.
